{% set name = "cfdm" %}
{% set version = "1.10.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fef88ca2d437c93a58c9ed3e89f914f92ec35b83b0907e57b29f0eb29f50cc8

build:
  number: 1
  skip: true  # [py<37]
  # has scripts and cannot be noarch
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - netcdf4 >=1.5.4
    - cftime >=1.6.0
    - numpy >=1.15
    - netcdf-flattener >=1.2.0
    - packaging >=20.0

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cfdm
  summary: A complete implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
