{% set name = "cfdm" %}
{% set version = "1.11.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f303f539a2bae1cd6dfb09e054e8b0ff35edc935feaf90bb04cf276bd07f3690

build:
  number: 0
  skip: true  # [py<37]
  # has scripts and cannot be noarch
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - scipy >=1.10.0
    - python
    - netcdf4 >=1.5.4
    - cftime >=1.6.0
    - numpy >=1.15
    - netcdf-flattener >=1.2.0
    - packaging >=20.0

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cfdm
  summary: A complete implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
