{% set name = "cfdm" %}
{% set version = "1.10.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a00ef1f0d76609b24a5a5c7eb4570e7469861df16496f6cb980cfc65cbd97017

build:
  number: 0
  # has scripts and cannot be noarch
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cftime >=1.6.0
    - netcdf-flattener >=1.2.0
    - netcdf4 >=1.5.4
    - numpy >=1.15
    - packaging >=20.0

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cfdm
  summary: A complete implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
