{% set name = "cfdm" %}
{% set version = "1.11.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9919cea8ef8604aa640dab8e457de4f2e5ab3e973bfac52f9fb9bea425c3d846

build:
  number: 0
  skip: true  # [py<37]
  # has scripts and cannot be noarch
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - dask-core >=2024.6.0,<=2024.7.1
    - h5netcdf >=1.3.0
    - h5py >=3.10.0
    - s3fs >=2024.6.0
    - scipy >=1.10.0
    - python
    - netcdf4 >=1.5.4
    - cftime >=1.6.0
    - numpy >=1.15,<2.0
    - netcdf-flattener >=1.2.0
    - packaging >=20.0

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cfdm
  summary: A complete implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
