{% set name = "cfdm" %}
{% set version = "1.9.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1783520821b44963a603f0732ec27035ddb98453c99a46a0e656c542fdfe8fcf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - cftime >=1.2.1
    - netcdf-flattener >=1.2.0
    - netcdf4 >=1.5.3
    - numpy >=1.15

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cfdm
  summary: A complete implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
