{% set name = "cfdm" %}
{% set version = "1.8.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 298b3b800cd80bfc5e7b69be9b82c786182c543bd1b804f0488133168c8f670f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cftime >=1.1.1
    - future >=0.16.0
    - netcdf4 >=1.5.3
    - numpy >=1.15

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cfdm
  summary: A complete implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
