{% set name = "cfdm" %}
{% set version = "1.10.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6605f34efba75bb36248f39b4c6b8b81f810714cc5ab940dbb9ff226c31a480

build:
  number: 0
  # has scripts and cannot be noarch
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cftime >=1.6.0
    - netcdf-flattener >=1.2.0
    - netcdf4 >=1.5.4
    - numpy >=1.15
    - packaging >=20.0

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cfdm
  summary: A complete implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
