{% set name = "cfdm" %}
{% set version = "1.13.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55ba3cb8157d0043fe93ca016cbe55b0038f271d5be3c4a8607c6bb114df9e16

build:
  number: 0
  # has scripts and cannot be noarch
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - xnetcdf >=0.1.0
    - fsspec >=2026.2.0
    - pyfive >=1.1.1
    - distributed >=2025.5.1
    - zarr >=3.0.8
    - python
    - cftime >=1.6.4
    - cfunits >=3.3.7
    - dask-core >=2025.5.1
    - h5netcdf >=1.8.1
    - h5py >=3.12.0
    - netcdf4 >=1.7.2
    - numpy >=2.0.0
    - packaging >=20.0
    - s3fs >=2024.6.0
    - scipy >=1.10.0
    - uritools >=4.0.3

test:
  imports:
    - cfdm
    - cfdm.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ncas-cms.github.io/cfdm
  summary: A Python reference implementation of the CF data model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidhassell
    - valeriupredoi
    - ocefpaf
